use_frameworks!

platform :ios, '9.0'

target 'DynamicMaskingLibrary_Example' do
  pod 'DynamicMaskingLibrary', :path => '../'

  target 'DynamicMaskingLibrary_Tests' do
    inherit! :search_paths

    
  end
end
